[build]
  command = "yarn build"
  publish = "_site"
  functions= "functions"

[[redirects]]
  from = "/thanks"
  to = "/home"
  status = 301
  force = false

[[redirects]]
  from = "/products/papertowels/paper-towels"
  to = "/products"
  status = 301
  force = false
  edge_handler = "get-paper"

  
